- templates/plugins/generic/htmlArticleGalley/css/default.css
To be consistent with theme styling.
> HTML Galley's links color

- styles/objects/article-details.less
> Managing too long URLs

- styles/objects/article-details.less
- templates/frontend/objects/article_details.tpl
Article landing page: copyright #28
> Placing licensing info after references block

- styles/objects/article-details.less
> Word break for how-to-cite block

- styles/components/header.less
Journal title on mobile view #25
> Removing hidden overflow for journal title

- styles/pages/page-view-pdf.less
- templates/plugins/generic/pdfJsViewer/templates/display.tpl
In PDF galley view download button wraps off the line #24
> Fix for pdf galley's header

- styles/objects/article-details.less
- templates/frontend/objects/article_details.tpl
- templates/frontend/objects/article_summary.tpl
Using a `getLocalizedFullTitle()` method
> #29 Article's title + subtitle block

- templates/frontend/pages/search.tpl
https://github.com/pkp/healthSciences/issues/58 #58
> Escaping search input

- templates/frontend/components/header.tpl
> Check whether primary menu exists #45

- styles/components/registrationForm.less
- templates/frontend/components/registrationForm.tpl
> consent upon registration

- HealthSciencesThemePlugin.inc.php
Related to #97, I thought I'd submit a pull request myself because I don't find any icons being used anywhere in the theme (yet), so this change should hopefully have minimal impact and save you some time. :)
> Change Font Awesome version from 4.7 to 5.2

- locale/nb_NO/locale.xml
We have translated the theme to Norwegian, are you interested in our locale file?
> Add nb_NO locale

- locale/nb_NO/locale.xml
For plugins.themes.healthSciences.article.supplementaryFiles.
> Add missing nb_NO locale string 

- README.md
Plus minor formatting proposals
> Typo on #49

- locale/es_ES/locale.xml
Spanish translation of the Health Sciences theme for OJS
> Spanish translation

- locale/pt_BR/locale.xml
Hi there!
i tried again, this time following your directions (thanks for that!). I hope it works. If it doesn't, please let me know.
Best,
Renato.
> Added pt_BR locale

- locale/fr_CA/locale.xml
I assume all I need to add here is the locale file.
> fr_CA added

- HealthSciencesThemePlugin.inc.php
- styles/components/buttons.less
- styles/objects/article-details.less
- styles/objects/issue-toc.less
- styles/pages/page-home.less
- styles/pages/page-view-html.less
- templates/plugins/generic/htmlArticleGalley/css/default.css
> Make sure all coloured text is relative to the primary colour

- styles/pages/page-home.less
> Update homepage cover style

- templates/frontend/objects/article_details.tpl
> Only display +/- for authors with bio or affiliation info

- locale/fr_FR/locale.xml
Hi, 
I have added a French (France) locale to the Health and Science Theme, using the FR_CA as a base with some minor edits.
> fr_FR locale

- HealthSciencesThemePlugin.inc.php
- styles/components/alerts.less
- styles/components/buttons.less
- styles/components/dropdowns.less
- styles/components/forms.less
- styles/components/header.less
- styles/components/modals.less
- styles/objects/issue-toc.less
- styles/pages/page-home.less
- styles/typography.less
- styles/variables.less
- templates/frontend/components/header.tpl
- templates/frontend/pages/indexJournal.tpl
- templates/frontend/pages/issue.tpl
- templates/frontend/pages/search.tpl
a11y-related stuff - increase colour contrast for text, depending on users’ brand colour selection (whether it is dark or pale)
> Colour adjustments

- js/main.js
- styles/components/registrationForm.less
> Fix tagit results showing a div at bottom of page #152

- js/main.js
see #173, solution adopted from default theme
> Registration form, updated tag-it init to retain reviewer interests when submit validation fails

- templates/frontend/components/registrationForm.tpl
- templates/frontend/pages/search.tpl
- templates/frontend/pages/userLostPassword.tpl
> Update input type

- templates/frontend/objects/article_summary.tpl
> Get the DOI to be displayed

- templates/frontend/components/loginForm.tpl
- templates/frontend/components/registrationForm.tpl
In response to https://github.com/pkp/pkp-lib/issues/6676
This is my first ever PR to any Git repo 😨 Please let me know if something should be done differently.
> Autocomplete attributes

- templates/frontend/pages/search.tpl
fixes https://github.com/pkp/healthSciences/issues/220
> fixes pkp/healthSciences/issues/220

- README.md
- templates/frontend/pages/issueArchive.tpl
- version.xml
Addresses 
https://github.com/pkp/healthSciences/issues/237
https://github.com/pkp/healthSciences/issues/235
https://forum.pkp.sfu.ca/t/problem-with-archive-in-health-sciences-theme/86266/6
> pkp/healthSciences#237 Fix layout misalignment for issue archive

- locale/fr_CA/locale.po
It looks like translation for this theme locales is not yet managed through https://translate.pkp.sfu.ca/projects/plugins/ (?) so I'm providing a revised version here. This former pull request can be cancelled : https://github.com/pkp/healthSciences/pull/193
> Update fr_CA translation
